CREATE TABLE habitats
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_habitats PRIMARY KEY (id)
);

CREATE TABLE monsters
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    gender             VARCHAR(255),
    race_id            BIGINT,
    species_id         BIGINT,
    habitat_id         BIGINT,
    age                VARCHAR(255),
    threat_level       INTEGER,
    description        TEXT,
    last_seen_location VARCHAR(255),
    wanted             VARCHAR(255),
    known_weaknesses   VARCHAR(255),
    image_prompt       TEXT,
    bounty_drakes      INTEGER,
    is_captured        BOOLEAN,
    termination_status VARCHAR(255),
    CONSTRAINT pk_monsters PRIMARY KEY (id)
);

CREATE TABLE races
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    alignment VARCHAR(255),
    lore      TEXT,
    CONSTRAINT pk_races PRIMARY KEY (id)
);

CREATE TABLE species
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_species PRIMARY KEY (id)
);

ALTER TABLE habitats
    ADD CONSTRAINT uc_habitats_name UNIQUE (name);

ALTER TABLE monsters
    ADD CONSTRAINT uc_monsters_name UNIQUE (name);

ALTER TABLE races
    ADD CONSTRAINT uc_races_name UNIQUE (name);

ALTER TABLE species
    ADD CONSTRAINT uc_species_name UNIQUE (name);

ALTER TABLE monsters
    ADD CONSTRAINT FK_MONSTERS_ON_HABITAT FOREIGN KEY (habitat_id) REFERENCES habitats (id);

ALTER TABLE monsters
    ADD CONSTRAINT FK_MONSTERS_ON_RACE FOREIGN KEY (race_id) REFERENCES races (id);

ALTER TABLE monsters
    ADD CONSTRAINT FK_MONSTERS_ON_SPECIES FOREIGN KEY (species_id) REFERENCES species (id);